In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
credits=pd.read_csv('Downloads/archive (1)/tmdb_5000_credits.csv')
movies=pd.read_csv('Downloads/archive (1)/tmdb_5000_movies.csv')

In [3]:
movies

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,220000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",NaN,9367,"[{""id"": 5616, ""name"": ""united states\u2013mexi...",es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,"[{""name"": ""Columbia Pictures"", ""id"": 5}]","[{""iso_3166_1"": ""MX"", ""name"": ""Mexico""}, {""iso...",1992-09-04,2040920,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238
4799,9000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,72766,[],en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,[],[],2011-12-26,0,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5
4800,0,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",http://www.hallmarkchannel.com/signedsealeddel...,231617,"[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...",en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,"[{""name"": ""Front Street Pictures"", ""id"": 3958}...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2013-10-13,0,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6
4801,0,[],http://shanghaicalling.com/,126186,[],en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,[],"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-05-03,0,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7
4802,0,"[{""id"": 99, ""name"": ""Documentary""}]",NaN,25975,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...",en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,"[{""name"": ""rusty bear entertainment"", ""id"": 87...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2005-08-05,0,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16

In [4]:
credits['title']

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...
4798                                 El Mariachi
4799                                   Newlyweds
4800                   Signed, Sealed, Delivered
4801                            Shanghai Calling
4802                           My Date with Drew
Name: title, Length: 4803, dtype: object

In [5]:
movies['keywords'].tail(5)

4798    [{"id": 5616, "name": "united states\u2013mexi...
4799                                                   []
4800    [{"id": 248, "name": "date"}, {"id": 699, "nam...
4801                                                   []
4802    [{"id": 1523, "name": "obsession"}, {"id": 224...
Name: keywords, dtype: object

In [6]:
display(movies['keywords'].head(),credits.head())

0    [{"id": 1463, "name": "culture clash"}, {"id":...
1    [{"id": 270, "name": "ocean"}, {"id": 726, "na...
2    [{"id": 470, "name": "spy"}, {"id": 818, "name...
3    [{"id": 849, "name": "dc comics"}, {"id": 853,...
4    [{"id": 818, "name": "based on novel"}, {"id":...
Name: keywords, dtype: object

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [7]:
movie_keywords = {}

for row in movies.iterrows():
    row = pd.Series(row)
    name = row[1]['original_title']
    keywords_list = json.loads(row[1]['keywords'])

    keyword_names = []

    for keyword in keywords_list:
        keyword_names.append(keyword['name'])

    movie_keywords[name] = keyword_names

In [8]:
print('Spider-Man:', len(movie_keywords['Spider-Man']))
movie_keywords['Spider-Man']

Spider-Man: 11

['loss of lover',
 'spider',
 'thanksgiving',
 'bad boss',
 'hostility',
 'marvel comic',
 'superhero',
 'pokies',
 'evil',
 'reference to superman',
 'goblin']

In [9]:
import nltk
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords

# Downloading and setting stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Setting up the regex tokenizer
tokenizer = RegexpTokenizer(r"\w+'t|\w+'ve|\w+").tokenize

[nltk_data] Downloading package stopwords to C:\Users\Priyanshu
[nltk_data]     singh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [10]:
movie_overview = {title: str(overview).lower() for title, overview in movies[['original_title', 'overview']].to_numpy()}

# Tokenising the overview for each movie
movie_overview = {movie: tokenizer(movie_overview[movie]) for movie in movie_keywords}

# Removing stopwords for the overview tokens for each movie
for movie in movie_overview:
    overview_keywords = [kw for kw in movie_overview[movie] if kw not in stop_words]
    movie_overview[movie] = overview_keywords

In [11]:
print(len(movie_overview['Spider-Man']))
movie_overview['Spider-Man']

13

['bitten',
 'genetically',
 'altered',
 'spider',
 'nerdy',
 'high',
 'school',
 'student',
 'peter',
 'parker',
 'endowed',
 'amazing',
 'powers']

In [12]:
# Combining given keywords as well as overview keywords
movie_keywords_all = {}

for movie in movie_keywords:
    movie_keywords_all[movie] = movie_keywords[movie] + movie_overview[movie]

In [13]:
print(len(movie_keywords_all['Spider-Man']))
movie_keywords_all['Spider-Man']

24

['loss of lover',
 'spider',
 'thanksgiving',
 'bad boss',
 'hostility',
 'marvel comic',
 'superhero',
 'pokies',
 'evil',
 'reference to superman',
 'goblin',
 'bitten',
 'genetically',
 'altered',
 'spider',
 'nerdy',
 'high',
 'school',
 'student',
 'peter',
 'parker',
 'endowed',
 'amazing',
 'powers']

In [14]:
#Importing sub-modules required for lemmatising
from nltk import pos_tag
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer

# Downloading required dependencies
# nltk.download("punkt")
nltk.download("averaged_perceptron_tagger_eng")
nltk.download("wordnet")

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\Priyanshu singh\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to C:\Users\Priyanshu
[nltk_data]     singh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [15]:
# Setting up lemmatiser
wnl = WordNetLemmatizer()

def get_wordnet_pos(tag):
    """Map NLTK POS tags to WordNet POS tags"""
    if tag.startswith("V"): return wordnet.VERB
    if tag.startswith("J"): return wordnet.ADJ
    if tag.startswith("R"): return wordnet.ADV
    return wordnet.NOUN  # default

In [16]:
# Extracting lemmas for all movies
movie_keywords_lemmas = {}
for movie in movie_keywords_all:
    tags = pos_tag(movie_keywords_all[movie])
    lemmas = [wnl.lemmatize(word, get_wordnet_pos(tag)) for word, tag in tags]
    movie_keywords_lemmas[movie] = lemmas

In [17]:
print(len(movie_keywords_lemmas['Spider-Man']))
movie_keywords_lemmas['Spider-Man']

24

['loss of lover',
 'spider',
 'thanksgiving',
 'bad boss',
 'hostility',
 'marvel comic',
 'superhero',
 'poky',
 'evil',
 'reference to superman',
 'goblin',
 'bite',
 'genetically',
 'alter',
 'spider',
 'nerdy',
 'high',
 'school',
 'student',
 'peter',
 'parker',
 'endow',
 'amazing',
 'power']

In [18]:
# Spltting multi-word expressions into separate words and appending them to the existing list of lemmas for each movie
movie_keywords_final={}
for movie in movie_keywords_lemmas:
    lemmas = movie_keywords_lemmas[movie]
    split_words = []

    for lemma in lemmas:
        if ' ' in lemma:
            split_words += lemma.split(' ')
    lemmas += split_words
    movie_keywords_final[movie] = lemmas

In [19]:
print(len(movie_keywords_final['Spider-Man']))
movie_keywords_final['Spider-Man']

34

['loss of lover',
 'spider',
 'thanksgiving',
 'bad boss',
 'hostility',
 'marvel comic',
 'superhero',
 'poky',
 'evil',
 'reference to superman',
 'goblin',
 'bite',
 'genetically',
 'alter',
 'spider',
 'nerdy',
 'high',
 'school',
 'student',
 'peter',
 'parker',
 'endow',
 'amazing',
 'power',
 'loss',
 'of',
 'lover',
 'bad',
 'boss',
 'marvel',
 'comic',
 'reference',
 'to',
 'superman']

In [20]:
# Remove stopwords from dictionary movies_keywords_final
movie_keywords_clean={}
for movie, keywords in movie_keywords_final.items():
    # Filter out stopwords
    filtered_keywords = [word for word in keywords if word.lower() not in stop_words]
    movie_keywords_clean[movie] = filtered_keywords
print(len(movie_keywords_clean['Spider-Man']))
movie_keywords_clean['Spider-Man']

32

['loss of lover',
 'spider',
 'thanksgiving',
 'bad boss',
 'hostility',
 'marvel comic',
 'superhero',
 'poky',
 'evil',
 'reference to superman',
 'goblin',
 'bite',
 'genetically',
 'alter',
 'spider',
 'nerdy',
 'high',
 'school',
 'student',
 'peter',
 'parker',
 'endow',
 'amazing',
 'power',
 'loss',
 'lover',
 'bad',
 'boss',
 'marvel',
 'comic',
 'reference',
 'superman']

In [21]:
result = (pd.Series(movie_keywords_clean)
            .explode()
            .reset_index()
            .rename(columns={'index': 'key', 0: 'items'}))

In [22]:
result

                      key          items
0                  Avatar  culture clash
1                  Avatar         future
2                  Avatar      space war
3                  Avatar   space colony
4                  Avatar        society
...                   ...            ...
212008  My Date with Drew      filmmaker
212009  My Date with Drew            new
212010  My Date with Drew         jersey
212011  My Date with Drew          dream
212012  My Date with Drew           girl

[212013 rows x 2 columns]

In [23]:
result_grouped = result.groupby(['key', 'items']).size().reset_index(name='count')
result_grouped

            key       items  count
0       #Horror          12      1
1       #Horror      actual      1
2       #Horror   addiction      1
3       #Horror       bully      1
4       #Horror  compulsive      1
...         ...         ...    ...
189197      해운대        wife      1
189198      해운대     without      1
189199      해운대       woman      1
189200      해운대       wound      1
189201      해운대        yeon      1

[189202 rows x 3 columns]

In [40]:

movie_docs = result_grouped.groupby('key')['items'].apply(' '.join).reset_index()
movie_docs.columns = ['movie', 'text']

In [42]:
movie_docs

,movie,text
0,#Horror,12 actual addiction bully compulsive cyber eve...
1,$upercapitalist,ability analytic beyond control deal escalate ...
2,(500) Days of Summer,500 affair angeles architect card caught compl...
3,...E tu vivrai nel terrore! L'aldilà,accident acid blindness blood build building d...
4,10 Cloverfield Lane,accident alien apocalypse attack awaken baseme...
...,...,...
4795,인천상륙작전,"""trudy battle crucial douglas fictionalized fi..."
4796,"좋은 놈, 나쁜 놈, 이상한 놈",1930s army bad bandit battle bounty chinese de...
4797,친절한 금자씨,13 6 action beautiful boy close closer daughte...
4798,태극기 휘날리며,18 1950 air air raid along archaeologist army ...
4799,해운대,agony anything axis beach behind call caution ...

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(max_features=5560)
tfidf_matrix = vectorizer.fit_transform(movie_docs['text'])

# Shape: (num_movies, num_unique_keywords)
print(tfidf_matrix.shape)

(4800, 5560)

In [45]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
# Result: NxN matrix where cosine_sim[i][j] = similarity between movie i and movie j
cosine_sim

array([[1.        , 0.        , 0.01051246, ..., 0.03002352, 0.01627918,
        0.00906595],
       [0.        , 1.        , 0.        , ..., 0.        , 0.        ,
        0.03694419],
       [0.01051246, 0.        , 1.        , ..., 0.00944406, 0.02315771,
        0.        ],
       ...,
       [0.03002352, 0.        , 0.00944406, ..., 1.        , 0.05526066,
        0.03637378],
       [0.01627918, 0.        , 0.02315771, ..., 0.05526066, 1.        ,
        0.07800586],
       [0.00906595, 0.03694419, 0.        , ..., 0.03637378, 0.07800586,
        1.        ]])

In [46]:
vb=pd.DataFrame(cosine_sim)
vb

,0,1,2,3,4,5,6,7,8,9,...,4790,4791,4792,4793,4794,4795,4796,4797,4798,4799
0,1.000000,0.000000,0.010512,0.060707,0.017875,0.030920,0.009483,0.000000,0.000000,0.027959,...,0.000000,0.010567,0.000000,0.000000,0.009536,0.000000,0.000000,0.030024,0.016279,0.009066
1,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.006250,0.006499,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036944
2,0.010512,0.000000,1.000000,0.000000,0.000000,0.067242,0.032015,0.009738,0.014328,0.017301,...,0.015169,0.008085,0.000000,0.000000,0.006884,0.011171,0.000000,0.009444,0.023158,0.000000
3,0.060707,0.000000,0.000000,1.000000,0.034123,0.019534,0.006311,0.000000,0.000000,0.007669,...,0.046693,0.016207,0.027825,0.000000,0.000000,0.000000,0.000000,0.011275,0.010345,0.003741
4,0.017875,0.000000,0.000000,0.034123,1.000000,0.000000,0.025675,0.016073,0.008805,0.038974,...,0.028533,0.095196,0.000000,0.000000,0.000000,0.000000,0.017753,0.042847,0.011035,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0.000000,0.000000,0.011171,0.000000,0.000000,0.000000,0.000000,0.000000,0.025246,0.000000,...,0.078218,0.008916,0.118091,0.081708,0.000000,1.000000,0.057238,0.000000,0.154775,0.023088
4796,0.000000,0.000000,0.000000,0.000000,0.017753,0.000000,0.025940,0.013487,0.000000,0.040417,...,0.048684,0.011659,0.081137,0.050856,0.000000,0.057238,1.000000,0.000000,0.074281,0.000000
4797,0.030024,0.000000,0.009444,0.011275,0.042847,0.043097,0.015356,0.007110,0.000000,0.014646,...,0.048363,0.026031,0.000000,0.019576,0.058450,0.000000,0.000000,1.000000,0.055261,0.036374
4798,0.016279,0.000000,0.023158,0.010345,0.011035,0.015061,0.015217,0.030664,0.058743,0.000000,...,0.151754,0.003596,0.290546,0.252183,0.055055,0.154775,0.074281,0.055261,1.000000,0.078006
4799,0.009066,0.036944,0.000000,0.003741,0.000000,0.005200,0.023532,0.010397,0.027514,0.000000,...,0.034444,0.044933,0.125953,0.063292,0.006454,0.023088,0.000000,0.036374,0.078006,1.000000

In [48]:
def recommend(movie_title, top_n=5):
    # Get index of the movie
    idx = movie_docs[movie_docs['movie'] == movie_title].index[0]
    
    # Get similarity scores for all movies vs. this movie
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    # Sort by similarity (descending), skip the movie itself (score=1.0)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    
    # Return top N recommended movies
    movie_indices = [i[0] for i in sim_scores]
    return movie_docs['movie'].iloc[movie_indices].tolist()

print(recommend("Evil Dead"))

['Khiladi 786', 'The Evil Dead', 'Halloween 4: The Return of Michael Myers', 'Extreme Ops', 'Jackass 3D']

In [49]:
result = (pd.Series(movie_keywords)
            .explode()
            .reset_index()
            .rename(columns={'index': 'key', 0: 'items'}))

In [ ]:
result_grouped_ = result.groupby(['key', 'items']).size().reset_index(name='count')

In [ ]:
result_grouped_

In [ ]:
result_grouped_ = result['items'].value_counts().reset_index()

In [ ]:
result_grouped_[result_grouped1['count']>3]

In [ ]:

movie_docs = result_grouped.groupby('key')['items'].apply(' '.join).reset_index()
movie_docs.columns = ['movie', 'text']

In [ ]:
movie_docs

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(movie_docs['text'])

# Shape: (num_movies, num_unique_keywords)
print(tfidf_matrix.shape)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)
# Result: NxN matrix where cosine_sim[i][j] = similarity between movie i and movie j

In [ ]:
cosine_sim

In [ ]:
def recommend(movie_title, top_n=5):
    # Get index of the movie
    idx = movie_docs[movie_docs['movie'] == movie_title].index[0]
    
    # Get similarity scores for all movies vs. this movie
    sim_scores = list(enumerate(cosine_sim[idx]))
    
    # Sort by similarity (descending), skip the movie itself (score=1.0)
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
    
    # Return top N recommended movies
    movie_indices = [i[0] for i in sim_scores]
    return movie_docs['movie'].iloc[movie_indices].tolist()

print(recommend("Evil Dead"))

In [ ]:
movie_docs[movie_docs['movie']=='Evil Dead']

In [ ]:
movies['keywords']

In [ ]:
credits['cast']